package com.example.smartshoppingcart.Model;
import jakarta.persistence.*;


/**
 * Entity representing a cart item in the shopping cart.
 * <p>
 * This class maps to the "cart_items" table in the database and contains details about each item in the cart.
 */
@Entity
@Table(name="cart_items")
public class CartModel {

    /**
     * The unique identifier for the cart item.
     * <p>
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the cart item.
     * <p>
     * Example: "Apple"
     */
    private String name;

    /**
     * The quantity of the cart item.
     * <p>
     * Example: 3
     */
    private int quantity;

    /**
     * The price of the cart item.
     * <p>
     * Example: 1.99
     */
    private double price;

    /**
     * Default constructor for CartModel.
     */
    public CartModel() {
    }

    /**
     * Parameterized constructor for CartModel.
     *
     * @param id       the unique identifier for the cart item
     * @param name     the name of the cart item
     * @param quantity the quantity of the cart item
     * @param price    the price of the cart item
     */
    public CartModel(Long id, String name, int quantity, double price) {
        this.id = id;
        this.name = name;
        this.quantity = quantity;
        this.price = price;
    }

    /**
     * Parameterized constructor for CartModel.
     *
     * @param name the name of the cart item
     * @param quantity the quantity of the cart item
     * @param price the price of the cart item
     */
    public CartModel(String name, int quantity, double price) {
        this.name = name;
        this.price = price;
        this.quantity = quantity;
    }

    /**
     * Gets the unique identifier for the cart item.
     *
     * @return the unique identifier for the cart item
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier for the cart item.
     *
     * @param id the unique identifier for the cart item
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the name of the cart item.
     *
     * @return the name of the cart item
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the cart item.
     *
     * @param name the name of the cart item
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the quantity of the cart item.
     *
     * @return the quantity of the cart item
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     * Sets the quantity of the cart item.
     *
     * @param quantity the quantity of the cart item
     */
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    /**
     * Gets the price of the cart item.
     *
     * @return the price of the cart item
     */
    public double getPrice() {
        return price;
    }

    /**
     * Sets the price of the cart item.
     *
     * @param price the price of the cart item
     */
    public void setPrice(double price) {
        this.price = price;
    }
}
