package com.example.smartshoppingcart.Model;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity representing a product in the application.
 * <p>
 * This class maps to the "products" table in the database and contains details about each product.
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "products")
public class Products {

    /**
     * Unique identifier for the product.
     * <p>
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the product.
     * <p>
     * Example: "Apple iPhone 13"
     */
    private String name;

    /**
     * Barcode of the product.
     * <p>
     * Example: "1234567890123"
     */
    private String barcode;

    /**
     * Description of the product.
     * <p>
     * Example: "Latest model of Apple iPhone with 128GB storage."
     */
    private String description;

    /**
     * Price of the product.
     * <p>
     * Example: 999.99
     */
    private Double price;

    /**
     * Stock of the product.
     * <p>
     * Example: 50
     */
    private Integer stock;

    /**
     * Image of the product.
     * <p>
     * Example: "<a href="http://example.com/images/iphone13.jpg">...</a>"
     */
    private String image;

    /**
     * Category of the product.
     * <p>
     * Example: "Electronics"
     */
    private String category;

    /**
     * Brand of the product.
     * <p>
     * Example: "Apple"
     */
    private String brand;

    /**
     * Weight of the product.
     * <p>
     * Example: 0.174
     */
    private Double weight;

    /**
     * Discount of the product.
     * <p>
     * Example: 0.10
     */
    private Double discount;

}
