package com.example.smartshoppingcart.Model;
import jakarta.persistence.*;
import lombok.*;

/**
 * Entity representing a shopping item in the application.
 * <p>
 * This class maps to the "shopping_item" table in the database and contains details about each item.
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ShoppingItem {

    /**
     * Unique identifier for the shopping item.
     * <p>
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * Identifier for the user associated with the shopping item.
     */
    private Integer userId; // Associate item with a user

    /**
     * Barcode of the shopping item.
     * <p>
     * Example: "1234567890123"
     */
    private String barcode;

    /**
     * Name of the shopping item.
     * <p>
     * Example: "Apple iPhone 13"
     */
    private String itemName;

    /**
     * Quantity of the shopping item.
     * <p>
     * Example: 2
     */
    private int quantity;

    /**
     * Weight of the shopping item.
     * <p>
     * Example: 0.5
     */
    private double weight;  // NEW FIELD
}
